In [1]:
import pickle
from pathlib import Path
import pandas as pd

In [2]:
video_root = Path('/root/data/raw/drive_and_act/')
annotation_path = video_root / 'iccv_activities_3s' / 'activities_3s' / 'inner_mirror' / 'midlevel.chunks_90.csv'
raw_ann_df = pd.read_csv(annotation_path)

In [3]:
# with open('output/inner_mirror_with_padding/incorrect/pose2D.pkl', 'rb') as f:
#     pose2d_list = pickle.load(f)

with open('output/inner_mirror_with_padding/frame_info.pkl', 'rb') as f:
    frame_info_list = pickle.load(f)

with open('output/inner_mirror_with_padding/annotation.pkl', 'rb') as f:
    annotation_df = pickle.load(f)
with open('output/inner_mirror_with_padding/pose_info.pkl', 'rb') as f:
    pose_info_list = pickle.load(f)

In [4]:
frame_info_df = pd.DataFrame(frame_info_list).set_index('frame_index')
# pose_2d_df = pd.DataFrame(pose2d_list)
pose_info_df = pd.DataFrame(pose_info_list).set_index('index').sort_index()
pose_df = frame_info_df.merge(pose_info_df, left_on='frame_index', right_on='index')

In [11]:
annotation_df

,participant_id,video_name,annotation_id,activity,frame_index_start,frame_index_end
0,1,vp1/run1b_2018-05-29-14-02-47.ids_1,0,standing_by_the_door,0,48
1,1,vp1/run1b_2018-05-29-14-02-47.ids_1,1,closing_door_outside,48,103
2,1,vp1/run1b_2018-05-29-14-02-47.ids_1,2,standing_by_the_door,103,152
3,1,vp1/run1b_2018-05-29-14-02-47.ids_1,3,opening_door_outside,152,211
4,1,vp1/run1b_2018-05-29-14-02-47.ids_1,4,entering_car,211,267
...,...,...,...,...,...,...
3298,15,vp15/run2_2018-05-30-13-34-33.ids_1,124,pressing_automation_button,700459,700493
3299,15,vp15/run2_2018-05-30-13-34-33.ids_1,125,unfastening_seat_belt,700493,700606
3300,15,vp15/run2_2018-05-30-13-34-33.ids_1,126,opening_door_inside,700606,700667
3301,15,vp15/run2_2018-05-30-13-34-33.ids_1,127,exiting_car,700667,700794
3302,15,vp15/run2_2018-05-30-13-34-33.ids_1,128,closing_door_outside,700794,700843

In [10]:
pose_df.loc[603211: 603211+15]

,participant_id,video_name,annotation_id,frame,activity,annotated_frame,pose_2d,root_2d,scale_factor_w,scale_factor_h,pose_3d
603211,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,135,entering_car,False,"[[0.17272646245396034, -0.31957091294645373], ...","[899.432078979447, 424.06862776822567]",434.084381,603.659870,"[[0.10224573314189911, -0.1146765872836113, -0..."
603212,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,137,entering_car,False,"[[0.5800790273832813, -0.16722949282321087], [...","[781.8234989154349, 326.27513506168884]",354.658390,608.107705,"[[0.22471512854099274, -0.09486074000597, 0.07..."
603213,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,139,entering_car,False,"[[0.590817798098818, -0.14313638690479116], [0...","[778.7019295260625, 316.71705118335393]",353.609040,618.202817,"[[0.23266449570655823, -0.08851958811283112, 0..."
603214,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,141,entering_car,False,"[[0.5744510830307591, -0.18835202663401343], [...","[775.0170639900058, 323.58502651264064]",372.516157,614.725586,"[[0.19423286616802216, -0.09501750022172928, 0..."
603215,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,143,entering_car,False,"[[0.5350808423078274, -0.16697534483589843], [...","[795.4108705036539, 325.39702630773866]",354.536253,630.184108,"[[0.24639074504375458, -0.11273884773254395, 0..."
603216,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,145,entering_car,False,"[[0.5780676207409509, -0.1678729132038006], [0...","[777.3350781113463, 324.31056710015974]",344.876157,631.491811,"[[0.22603997588157654, -0.1312876045703888, 0...."
603217,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,147,entering_car,False,"[[0.7818774246161958, -0.18981963778815625], [...","[707.3601188806811, 311.3033314649972]",351.885616,604.422703,"[[0.22012510895729065, -0.08831688016653061, 0..."
603218,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,149,entering_car,False,"[[0.6996861641981681, -0.15016576294830686], [...","[722.7149209348103, 315.00934865576414]",362.756004,643.615780,"[[0.2588843107223511, -0.10326535999774933, 0...."
603219,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,151,entering_car,False,"[[0.6695252362485359, -0.15829738975236132], [...","[724.387641267806, 311.9292556923913]",375.797915,606.937119,"[[0.21160253882408142, -0.08333346247673035, 0..."
603220,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,153,entering_car,False,"[[0.7612605408903962, -0.18418453759059514], [...","[720.6560128066151, 314.1127641202]",342.783261,631.152896,"[[0.21789748966693878, -0.08748665452003479, 0..."
603221,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,155,entering_car,False,"[[0.7463188107759565, -0.15987406460143533], [...","[724.0897122841602, 317.04742669751863]",342.977488,649.044081,"[[0.23389782011508942, -0.10827138274908066, 0..."
603222,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,157,entering_car,False,"[[0.4938075723717511, -0.16696981292789842], [...","[722.2790142403953, 308.85847403628657]",519.368579,669.240248,"[[0.16567282378673553, -0.09707997739315033, 0..."
603223,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,159,entering_car,False,"[[0.7217995660695202, -0.18268373830505652], [...","[730.4558365447643, 323.75241570551145]",343.290406,629.659356,"[[0.19794803857803345, -0.0738910436630249, 0...."
603224,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,161,entering_car,False,"[[0.5868575682774932, -0.17336973699500316], [...","[718.9562032776967, 311.8219232362952]",437.541747,593.163418,"[[0.21598920226097107, -0.12729482352733612, 0..."
603225,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,163,entering_car,False,"[[0.5443863889786164, -0.1650640105785557], [0...","[734.051321120959, 309.88804075791205]",445.594300,600.776425,"[[0.18588441610336304, -0.10046026110649109, 0..."
603226,14,vp14/run1_2018-05-30-10-11-09.ids_1,1,165,entering_car,True,"[[0.2183089154687911, -0.23447632997043735], [...","[877.0253997199552, 359.54286926494]",478.239748,612.717228,"[[0.0724669024348259, -0.08828549087047577, -0..."